# Generated by Django 5.2.1 on 2025-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['id'], 'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterField(
            model_name='enquete',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta', max_length=20),
        ),
    ]
